Add the Arabic.ahk file
popcar2/Franco_AHK pull request #2
Opened 2024-03-05 18:13 UTC by anthonyyoussef01

- Basically just the opposite of the Franco.ahk

2024-03-06 11:25 UTC, popcar2 requested changes
I'm not 100% sure why you'd want to write arabic --> franco but it looks fine. Just need to fix this one typo that causes an error.

2024-03-06 11:25 UTC, popcar2 commented on Arabic.ahk
> +    Send, {BackSpace}%
This should be `% and not just %

2024-03-06 13:13 UTC, anthonyyoussef01 commented on Arabic.ahk
> +    Send, {BackSpace}%
😂

2024-03-11 13:40 UTC, merged

2024-03-11 22:00 UTC, anthonyyoussef01 commented
I'd love it if you could take a look at my Qamous project (https://github.com/anthonyyoussef01/Qamous)